//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TowersOfHanoi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TowersOfHanoi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Een grotere schijf kan niet op een kleinere geplaatst worden..
        /// </summary>
        internal static string LargerDiscCannotBePutOnTopOfSmallerDisc
        {
            get
            {
                return ResourceManager.GetString("LargerDiscCannotBePutOnTopOfSmallerDisc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to De schijven zijn niet van vershillende grootte..
        /// </summary>
        internal static string LevelsAreNotUnique
        {
            get
            {
                return ResourceManager.GetString("LevelsAreNotUnique", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Er zijn meerdere toren met schijven..
        /// </summary>
        internal static string MoreThanOneTowerIsInitializedWithDiscs
        {
            get
            {
                return ResourceManager.GetString("MoreThanOneTowerIsInitializedWithDiscs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The indexes of towers cannot be the same..
        /// </summary>
        internal static string TowerIndexesCannotBeTheSame
        {
            get
            {
                return ResourceManager.GetString("TowerIndexesCannotBeTheSame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is out of range..
        /// </summary>
        internal static string TowerIndexOutOfRange
        {
            get
            {
                return ResourceManager.GetString("TowerIndexOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toren is niet goed geinitialiseerd..
        /// </summary>
        internal static string TowerIsNotConeShaped
        {
            get
            {
                return ResourceManager.GetString("TowerIsNotConeShaped", resourceCulture);
            }
        }
    }
}
